server:
  port: 0

app:
  client:
    url: http://SuperMart.com

spring:
  application:
    name: user-management
  datasource:
    url: jdbc:postgresql://localhost:5432/user_mgnt
    username: 'postgres'
    password: '12345678'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

encryption:
  salt:
    rounds: 10